"""edit settings table

Revision ID: f384328bda51
Revises: 34ed13e5e723
Create Date: 2024-05-27 22:29:39.591272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f384328bda51'
down_revision = '34ed13e5e723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_origin', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('route_destination', sa.String(length=128), nullable=False))
        batch_op.drop_column('transportation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transportation', sa.BLOB(), nullable=False))
        batch_op.drop_column('route_destination')
        batch_op.drop_column('route_origin')

    # ### end Alembic commands ###
